#!/bin/bash

set -u
set -e
dir=$(dirname $0)/../redis_data/
which realpath >/dev/null && dir=$(realpath $dir)
dest=$dir/dump.rdb
pushd $(dirname $0)/../ &>/dev/null

set +e
which s3cmd >/dev/null
[ $? -ne 0 ] && echo "You need the s3cmd installed (and configured)" && exit 1
which lzop >/dev/null
[ $? -ne 0 ] && echo "You need lzop installed" && exit 1
set -e

get_from_s3() {
    chmod 777 $dir || true
    pushd $dir &>/dev/null
    echo "Downloading $1"
    s3cmd get --force $1 ._s3file
    if [[ $1 == *.lzo ]]; then
        echo "Unpacking $1 to $dest"
        lzop -d -f ._s3file -o $dest
        rm -f ._s3file
    else
        mv ._s3file $dest
    fi
    echo "Fixing permissions"
    chmod 666 $dest || true
}

docker_config() {
    echo "Configuring docker"
    b2d=$(which 'boot2docker') || true
    if [ ! -z $b2d ] && [ -z $DOCKER_HOST ]; then
        export DOCKER_HOST="tcp://$($b2d ip 2>/dev/null):$($b2d cfg 2>/dev/null | grep DockerPort | cut -d' ' -f3)"
    fi
}

stop_containers() {
    echo "Removing containers"
    rake docker:remove
    echo -n "Removing redis dump: "
    rm -vf $dest
}

start_containers() {
    rake docker:up
    echo "Migrating data: rake docker:run ./bin/gaptool_server_migrate_0.5-0.6"
    rake docker:run ./bin/gaptool_server_migrate_0.5-0.6
}

if [ $# -eq 1 ]; then
    docker_config
    stop_containers
    if [[ $1 == s3://* ]]; then
        if echo $1 | grep -q '*'; then
            echo "Searching for last backup in $1"
            file=$(s3cmd ls $1 | sort -n -k1,2 | tail -n 1 | awk '{print $4}')
            [ -z $file ] && echo "Cannot find any backup in $1" && exit 1
            echo "Found: $file"
        else
            file=$1
        fi
        get_from_s3 $file
    else
        echo "Copying $1 to $dest"
        if [[ $1 == *.lzo ]]; then
            echo "Unpacking $1 to $dest"
            lzop -d -f $1 -o $dest
        else
            cp $1 $dest
        fi
        chmod 666 $dest
        chmod 777 $dir
    fi
    start_containers
else
    echo "usage: $(basename $0) <backup_location>"
    echo ""
    echo "<backup_location>"
    echo -e "\t * s3://<bucket>/<prefix>* : Download last backup from s3 bucket"
    echo -e "\t * s3://<bucket>/<prefix>/<file> : Download a specific file from s3"
    echo -e "\t * <path> : Copy a file from a local path"
    echo ""
    echo ".lzo files will be automatically uncompressed"
fi
